Repository GSG-G13/ntherapy-react, pull requests merged in 2023-06, with the labels that each got.

#1 Setting-up Front-End File Structure
  .eslintrc.cjs
  .gitignore
  README.md
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.tsx
  src/assets/react.svg
  src/components/index.tsx
  src/hooks/index.ts
  src/index.css
  src/layout/index.ts
  src/main.tsx
  src/pages/index.ts
  src/routes/index.ts
  src/utils/apis/index.ts
  src/utils/assets/index.ts
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: Waiting

#2 FE | Pages Routes
  package-lock.json
  package.json
  src/App.tsx
  src/layout/Layout.tsx
  src/main.tsx
  src/pages/admin/index.tsx
  src/pages/index.ts
  src/pages/landingPage/index.tsx
  src/pages/login/index.tsx
  src/pages/loginAdmin/index.tsx
  src/pages/notFound/index.tsx
  src/pages/signup/index.tsx
  src/pages/therapistProfile/index.tsx
  src/pages/therapists/index.tsx
  src/routes/index.ts
  src/routes/index.tsx
Labels: request-changes

#4 build: create doctor card UI
  package-lock.json
  package.json
  src/components/TherapistCard/classes.ts
  src/components/TherapistCard/index.tsx
  src/pages/therapists/index.tsx
  src/theme/theme.ts
Labels: Waiting to review

#6 Eslint setup airbnb
  .eslintrc.cjs
  .gitignore
  .husky/pre-commit
  .vscode/settings.json
  package-lock.json
  package.json
  src/components/TherapistCard/classes.ts
  src/components/TherapistCard/index.tsx
  src/layout/Layout.tsx
  src/main.tsx
  src/pages/admin/index.tsx
  src/pages/index.ts
  src/pages/landingPage/index.tsx
  src/pages/login/index.tsx
  src/pages/loginAdmin/index.tsx
  src/pages/notFound/index.tsx
  src/pages/signup/index.tsx
  src/pages/therapistProfile/index.tsx
  src/pages/therapists/index.tsx
  src/routes/index.tsx
  src/theme/theme.ts
  src/utils/apis/axios.ts
Labels: done

#7 create login page
  .vscode/settings.json
  package-lock.json
  package.json
  src/assets/loginImg.jpg
  src/pages/index.ts
  src/pages/login/classes.ts
  src/pages/login/index.tsx
  src/pages/login/schema.ts
  src/pages/login/style.css
  src/pages/loginAdmin/index.tsx
Labels: Waiting to review

#11 CI: setup github action for lint
  .github/workflows/lint-check.yml
Labels: awaiting-review

#16 [NTH-80] - Set token at axios request Header
  src/pages/landingPage/index.tsx
  src/utils/apis/axios.ts
Labels: done

#15 [NTH-64] create Model Appointments
  package-lock.json
  package.json
  src/components/AppointmentsModal/classes.ts
  src/components/AppointmentsModal/index.tsx
  src/components/AppointmentsModal/schema.ts
  src/components/index.tsx
  src/pages/therapistProfile/index.tsx
Labels: awaiting-review

#19 [NTH-83] Therapists Page Integration /therapist
  src/components/TherapistCard/classes.ts
  src/components/TherapistCard/index.tsx
  src/components/TherapistCard/types.ts
  src/components/TherapistsList/classes.ts
  src/components/TherapistsList/index.tsx
  src/components/index.tsx
  src/pages/therapists/classes.ts
  src/pages/therapists/index.tsx
  src/utils/apis/index.ts
Labels: awaiting-review

#18 [NTH-69] feat: therapist appointment table
  .eslintrc.cjs
  src/components/appointmentsTable/date/datePicker.tsx
  src/components/appointmentsTable/index.tsx
  src/components/appointmentsTable/table/index.tsx
  src/components/appointmentsTable/table/style.tsx
  src/components/appointmentsTable/table/tableRow.tsx
  src/components/appointmentsTable/table/types.ts
  src/components/index.tsx
  src/pages/therapistProfile/index.tsx
  vite.config.ts
Labels: request-changes

#17 [NTH-66] select date and Time for user and handle payment
  .env.development
  .env.production
  package-lock.json
  package.json
  src/components/bookappointment/modal/classes.ts
  src/components/bookappointment/modal/index.tsx
  src/components/bookappointment/modal/validation.ts
  src/components/bookappointment/payment/index.tsx
  src/components/bookappointment/selectTime/index.tsx
  src/components/bookappointment/selectTime/type.ts
  src/components/checkoutform/index.tsx
  src/components/index.tsx
  src/pages/index.ts
  src/pages/login/validationSchema.ts
  src/pages/therapistProfile/classes.ts
  src/pages/therapistProfile/index.tsx
  src/utils/TimeRange.ts
Labels: request-changes

#20 [NTH-85] User Login Form Submission and Access Token Storage
  package-lock.json
  src/pages/login/index.tsx
Labels: request-changes
