Repository GSG-G13/ntherapy-react, pull requests merged in 2023-07, with the labels that each got.

#23 Therapist profile page from user and therapist
  .env.development
  .vscode/settings.json
  package-lock.json
  package.json
  src/assets/profileImage.jpg
  src/components/appointmentsTable/date/datePicker.tsx
  src/components/appointmentsTable/index.tsx
  src/components/appointmentsTable/table/style.tsx
  src/components/index.tsx
  src/components/therapistProfile/changeBio/index.tsx
  src/components/therapistProfile/changeBio/types.ts
  src/components/therapistProfile/changePhoto/classes.ts
  src/components/therapistProfile/changePhoto/index.tsx
  src/components/therapistProfile/changePhoto/types.ts
  src/components/therapistProfile/index.ts
  src/components/therapistProfile/textFieldWithEdited/index.tsx
  src/components/therapistProfile/textFieldWithEdited/style.ts
  src/components/therapistProfile/textFieldWithEdited/types.ts
  src/components/therapistProfile/therapistHeader/classes.ts
  src/components/therapistProfile/therapistHeader/index.tsx
  src/components/therapistProfile/therapistHeader/types.ts
  src/pages/index.ts
  src/pages/signup/index.tsx
  src/pages/therapistProfile/classes.ts
  src/pages/therapistProfile/index.tsx
Labels: request-changes

#27 [NTH-91] using useContext
  src/context/authContext .tsx
  src/context/contextData.ts
  src/context/index.ts
  src/context/spinner.tsx
  src/context/types.ts
  src/main.tsx
  src/pages/therapistProfile/index.tsx
Labels: request-changes

#24 [NTH-109] Signup Integration
  src/pages/signup/index.tsx
  src/pages/signup/schema.ts
Labels: awaiting-review

#25 [NTH-88] feat: Admin login component
  package-lock.json
  package.json
  src/index.css
  src/pages/loginAdmin/adminSchema.ts
  src/pages/loginAdmin/index.tsx
  src/pages/loginAdmin/style.ts
Labels: Waiting to review, request-changes

#26 [NTH-108] landing page
  src/assets/img/World.png
  src/assets/img/group.png
  src/assets/img/hero.png
  src/assets/img/icon (1).png
  src/assets/img/icon (2).png
  src/assets/img/icon (3).png
  src/assets/img/icon (4).png
  src/assets/img/meet.png
  src/assets/img/online.png
  src/assets/img/online2.png
  src/assets/index.tsx
  src/components/landingPage/World.tsx
  src/components/landingPage/heroSection.tsx
  src/components/landingPage/index.tsx
  src/components/landingPage/onlineMedical.tsx
  src/components/landingPage/personalized.tsx
  src/components/landingPage/questions.tsx
  src/components/landingPage/services.tsx
  src/components/landingPage/style.css
  src/pages/landingPage/index.tsx
  src/pages/landingPage/styles.ts
Labels: awaiting-review

#28 [NTH-111] feat: patch profile image
  .github/workflows/check-build.yml
  src/components/therapistProfile/therapistHeader/index.tsx
Labels: awaiting-review

#31 [NTH-96] DOC: Create Readme
  README.md
Labels: documentation, awaiting-review

#30 use Navigate and added an appointment
  src/components/AppointmentsModal/index.tsx
  src/components/TherapistCard/index.tsx
  src/components/TherapistCard/types.ts
  src/components/appointmentsTable/date/datePicker.tsx
  src/components/appointmentsTable/index.tsx
  src/components/appointmentsTable/table/style.tsx
  src/components/bookappointment/selectTime/index.tsx
  src/components/therapistProfile/changeBio/index.tsx
  src/components/therapistProfile/changePhoto/index.tsx
  src/components/therapistProfile/changePhoto/types.ts
  src/components/therapistProfile/textFieldWithEdited/index.tsx
  src/components/therapistProfile/textFieldWithEdited/types.ts
  src/components/therapistProfile/therapistHeader/classes.ts
  src/components/therapistProfile/therapistHeader/index.tsx
  src/components/therapistProfile/therapistHeader/types.ts
  src/pages/login/index.tsx
  src/pages/login/schema.ts
  src/pages/login/validationSchema.ts
  src/pages/therapistProfile/index.tsx
Labels: awaiting-review

#35 [NTH-105] Footer section
  package-lock.json
  src/components/footer/classes.ts
  src/components/footer/index.tsx
  src/components/logo/index.tsx
  src/layout/Layout.tsx
Labels: awaiting-review

#32 [NTH-97] NOT Found Page
  README.md
  package-lock.json
  package.json
  src/pages/notFound/index.tsx
Labels: awaiting-review

#33 [NTH-101]
  index.html
  package-lock.json
  public/NTH.png
  src/components/dashboard/filter/filter.tsx
  src/components/dashboard/table/therapists/BodyTable.tsx
  src/components/dashboard/table/therapists/TableHeader.tsx
  src/components/dashboard/table/therapists/classes.ts
  src/components/dashboard/table/therapists/index.tsx
  src/components/dashboard/table/therapists/rowTable.tsx
  src/components/dashboard/table/therapists/types.ts
  src/pages/admin/index.tsx
Labels: Waiting to review

#39 fix: request body changed
  src/pages/loginAdmin/index.tsx
Labels: awaiting-review

#41 fix: start command
  package.json
Labels: done

#45 Booksend email
  .env.development
  src/components/TherapistCard/index.tsx
  src/components/bookappointment/modal/index.tsx
  src/components/bookappointment/payment/index.tsx
  src/components/checkoutform/index.tsx
  src/components/therapistProfile/therapistHeader/index.tsx
  src/context/authContext.tsx
  src/layout/Navbar.tsx
  src/pages/loginAdmin/index.tsx
  src/routes/protected.tsx
  vercel.json
Labels: awaiting-review

#46 fix: fix photo add settimestamp
  src/components/TherapistCard/index.tsx
  src/components/therapistProfile/therapistHeader/index.tsx
  src/layout/Navbar.tsx
Labels: awaiting-review

#51 [NTH-123]: add input select PriceFilter
  src/pages/therapists/classes.ts
  src/pages/therapists/index.tsx
Labels: awaiting-review

#53 fix: add responsive in signIn SignUp
  src/pages/login/index.tsx
  src/pages/login/style.css
  src/pages/signup/index.tsx
  src/pages/signup/style.css
Labels: awaiting-review

#56 build: add input responsive
  src/pages/therapists/classes.ts
  src/pages/therapists/index.tsx
Labels: awaiting-review

#57 Dark theme
  package-lock.json
  package.json
  src/App.tsx
  src/components/TherapistCard/index.tsx
  src/components/appointmentsTable/table/style.tsx
  src/components/appointmentsTable/table/tableRow.tsx
  src/components/footer/classes.ts
  src/components/landingPage/World.tsx
  src/components/landingPage/heroSection.tsx
  src/components/landingPage/questions.tsx
  src/components/landingPage/services.tsx
  src/components/landingPage/style.css
  src/components/therapistProfile/changeBio/index.tsx
  src/components/therapistProfile/changeBio/types.ts
  src/components/therapistProfile/textFieldWithEdited/index.tsx
  src/components/therapistProfile/textFieldWithEdited/style.ts
  src/components/therapistProfile/textFieldWithEdited/types.ts
  src/components/therapistProfile/therapistHeader/index.tsx
  src/context/index.ts
  src/context/themeContext.ts
  src/context/themeProvider.tsx
  src/index.css
  src/layout/Navbar.tsx
  src/main.tsx
  src/pages/landingPage/index.tsx
  src/pages/landingPage/style.css
  src/pages/therapistProfile/index.tsx
  src/pages/therapists/index.tsx
  src/theme/theme.ts
Labels: awaiting-review

#58 fix: fix color yellow to good color hhh
  src/theme/theme.ts
Labels: awaiting-review
